# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2022-10-01 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20220926_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_p', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('agg_cantidad', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('agg_por', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad_pedido', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('pedido_por', models.CharField(blank=True, max_length=50, null=True)),
                ('pedido_a', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=50, null=True)),
                ('reganizar_nvl', models.IntegerField(blank=True, default='0', null=True)),
                ('actualizacion_reciente', models.DateTimeField(auto_now=True)),
                ('exportar_a_CSV', models.BooleanField(default=False)),
            ],
        ),
    ]
