# Generated by Django 3.2.16 on 2022-10-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_auto_20221007_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
