# Generated by Django 3.2.16 on 2022-10-08 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_solicitud_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborador',
            old_name='numtel',
            new_name='numero_de_telefono',
        ),
    ]
