# Generated by Django 3.2.16 on 2022-10-14 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_rename_numtel_colaborador_numero_de_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='sueldo',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='credito',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.cliente'),
        ),
        migrations.AlterField(
            model_name='existencia',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.producto'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.cliente'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.colaborador'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='pago',
            field=models.PositiveIntegerField(),
        ),
    ]
