# Generated by Django 3.2.16 on 2022-10-16 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_auto_20221016_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='pago',
        ),
    ]
