# Generated by Django 3.2.16 on 2022-10-17 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0016_remove_solicitud_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credito',
            old_name='cliente',
            new_name='solicitud',
        ),
    ]
