# Generated by Django 3.2.16 on 2022-10-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0017_rename_cliente_credito_solicitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='nombre_p',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='actualizacion_reciente',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='agg_cantidad',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='agg_por',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='cantidad_pedido',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='exportar_a_CSV',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='pedido_a',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='pedido_por',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='reganizar_nvl',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Existencia',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
