# Generated by Django 3.2.16 on 2022-10-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0018_auto_20221016_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventario',
            name='medida',
            field=models.CharField(choices=[('u', 'u'), ('g', 'g'), ('l', 'l')], default='u', max_length=10),
        ),
    ]
