# Generated by Django 3.2.16 on 2022-10-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0019_auto_20221016_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='medida',
            field=models.CharField(choices=[('unidad', 'unidad'), ('gramos', 'gramos'), ('miligramos', 'mililitro')], default='u', max_length=10),
        ),
    ]
