# Generated by Django 3.2.16 on 2022-10-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0021_auto_20221017_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='dirreccion',
            new_name='direccion',
        ),
        migrations.AddField(
            model_name='detallecomprobantecompra',
            name='total',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
