# Generated by Django 3.2.16 on 2022-10-18 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0022_auto_20221017_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteServicio',
            fields=[
                ('nocomp', models.AutoField(primary_key=True, serialize=False)),
                ('fechav', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('gestion', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='categorias',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credito',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UnidadVendida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('preciouni', models.IntegerField(default=1)),
                ('totalprecio', models.IntegerField(default=1)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidadvendida', to='principal.inventario')),
                ('nocomp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compnoventa', to='principal.comprobanteservicio')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleComprobanteServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiposervicio', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.CharField(blank=True, max_length=50, null=True)),
                ('nocomp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saledetailsbillno', to='principal.comprobanteservicio')),
            ],
        ),
    ]
