# Generated by Django 3.2.16 on 2022-10-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0023_auto_20221018_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteservicio',
            name='servicio',
            field=models.PositiveIntegerField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comprobanteservicio',
            name='gestion',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
