# Generated by Django 3.2.16 on 2022-10-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0025_auto_20221025_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='cantidadmin',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
